WITH temp as (
    SELECT b.AUTHOR_ID, b.CATEGORY, SUM(s.SALES * b.PRICE) AS TOTAL_SALES
    FROM BOOK b
    JOIN BOOK_SALES s
    USING(BOOK_ID)
    WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m') = '2022-01'
    GROUP BY b.AUTHOR_ID, b.CATEGORY
)

SELECT a.AUTHOR_ID, a.AUTHOR_NAME, t.CATEGORY, t.TOTAL_SALES
FROM temp t
JOIN AUTHOR a
ON t.AUTHOR_ID = a.AUTHOR_ID
ORDER BY a.AUTHOR_ID, t.CATEGORY DESC;