SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((PRICE * SALES)) AS TOTAL_SALES
FROM BOOK_SALES bs
JOIN BOOK b ON bs.BOOK_ID = b.BOOK_ID
JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
AND DATE_FORMAT(bs.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY a.AUTHOR_ID, CATEGORY DESC;
