WITH temp as (
    SELECT CART_ID, COUNT(DISTINCT(NAME)) AS CNT
    FROM CART_PRODUCTS
    WHERE NAME IN ('Milk', 'Yogurt')
    GROUP BY CART_ID
)

SELECT CART_ID
FROM temp
WHERE CNT = 2
ORDER BY CART_ID;