SELECT e.ID, IFNULL(temp.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA e
LEFT OUTER JOIN (
    SELECT PARENT_ID, COUNT(*) AS CNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID) AS temp
ON e.ID = temp.PARENT_ID
ORDER BY e.ID;