WITH temp AS (
    SELECT PARENT_ID, COUNT(*) AS CNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL
)

SELECT e.ID, IFNULL(CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA e
LEFT OUTER JOIN temp t
ON e.ID = t.PARENT_ID
ORDER BY e.ID;