WITH UNAVAIL_CAR AS (
    SELECT CAR_ID,
        SUM(CASE
            WHEN END_DATE < '2022-11-01' OR START_DATE > '2022-11-30' THEN 0
            ELSE 1
        END) AS FLAG 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING FLAG > 0
),
TOTAL_PRICE AS (
    SELECT c.CAR_ID, c.CAR_TYPE, (c.DAILY_FEE * 30 * (1.0 - p.DISCOUNT_RATE * 0.01)) AS PRICE
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON c.CAR_TYPE = p.CAR_TYPE
    WHERE c.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM UNAVAIL_CAR
    ) AND p.DURATION_TYPE = '30일 이상'
)

SELECT CAR_ID, CAR_TYPE, ROUND(PRICE, 0) AS FEE
FROM TOTAL_PRICE
WHERE PRICE >= 500000 AND PRICE < 2000000
ORDER BY PRICE DESC, CAR_TYPE, CAR_ID;
