WITH temp AS(
    SELECT c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE,
        SUM(CASE
            WHEN (h.END_DATE < '2022.11.1' || h.START_DATE > '2022.11.30') THEN 0
            ELSE 1
        END) AS CNT, '30일 이상' AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c
    ON h.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE IN ('세단', 'SUV')
    GROUP BY CAR_ID
)

SELECT t.CAR_ID, t.CAR_TYPE, 
        FLOOR(t.DAILY_FEE * (1.0 - p.DISCOUNT_RATE * 0.01) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
JOIN temp t
ON p.CAR_TYPE = t.CAR_TYPE
AND p.DURATION_TYPE = t.DURATION_TYPE
WHERE t.CNT = 0
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, t.CAR_TYPE, t.CAR_ID DESC;