WITH temp AS (
    SELECT c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE,
    SUM(CASE
        WHEN h.START_DATE > '2022-11-30' OR h.END_DATE < '2022-11-01' OR NULL THEN 0
        ELSE 1
    END) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    RIGHT JOIN CAR_RENTAL_COMPANY_CAR c
    ON h.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE IN ('SUV', '세단')
    GROUP BY c.CAR_ID
)

SELECT temp.CAR_ID, temp.CAR_TYPE, FLOOR((temp.DAILY_FEE * 30) * (1 - 0.01 * p.discount_rate)) AS FEE
FROM temp
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON temp.CAR_TYPE = p.CAR_TYPE
WHERE p.duration_type = '30일 이상' AND temp.CNT = 0
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, temp.CAR_TYPE ASC, temp.CAR_ID DESC;