WITH temp AS (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_ID
)

SELECT t.YEAR, t.MONTH, u.GENDER, COUNT(*) AS USERS
FROM temp t
JOIN USER_INFO u
ON t.USER_ID = u.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY t.YEAR, t.MONTH, u.GENDER
ORDER BY t.YEAR, t.MONTH, u.GENDER;