SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH,
    COUNT(DISTINCT(u.USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(u.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO u
                                        WHERE u.JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM USER_INFO u
JOIN ONLINE_SALE o
ON u.USER_ID = o.USER_ID
WHERE u.JOINED LIKE '2021%'
GROUP BY MONTH(o.SALES_DATE)
ORDER BY YEAR, MONTH;