WITH temp AS (
    SELECT
        CASE
            WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
            ELSE '4Q'
        END AS ECOLI
    FROM ECOLI_DATA
)

SELECT ECOLI AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM temp
GROUP BY ECOLI
ORDER BY QUARTER;