WITH temp AS(
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY PRODUCT_ID
)

SELECT f.PRODUCT_ID, f.PRODUCT_NAME, f.PRICE * t.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT f
JOIN temp t
ON f.PRODUCT_ID = t.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, f.PRODUCT_ID;
