WITH temp AS(
    SELECT c.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) AS FEE,
    r.HISTORY_ID, c.CAR_TYPE,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY r
    ON c.CAR_ID = r.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
)

SELECT t.HISTORY_ID, 
    CASE 
        WHEN t.DURATION_TYPE IS NULL THEN t.FEE
        ELSE FLOOR(t.FEE * (1.0 - DISCOUNT_RATE * 0.01))
    END AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
RIGHT OUTER JOIN temp t
ON d.CAR_TYPE = t.CAR_TYPE
AND d.DURATION_TYPE = t.DURATION_TYPE
ORDER BY FEE DESC, t.HISTORY_ID DESC;
