WITH temp AS (
    SELECT HISTORY_ID, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS TERM,
        CAR_TYPE,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c
    ON h.CAR_ID = c.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID,
    FLOOR(CASE
        WHEN DURATION IS NULL THEN TERM * DAILY_FEE
        ELSE TERM * DAILY_FEE * (100 - DISCOUNT_RATE) * 0.01
    END) AS FEE
FROM temp t
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON t.DURATION = p.DURATION_TYPE
AND t.CAR_TYPE = p.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;