SELECT f.FLAVOR
FROM FIRST_HALF f
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS t
ON f.FLAVOR = t.FLAVOR
ORDER BY (f.TOTAL_ORDER + t.TOTAL_ORDER) DESC
LIMIT 3;