WITH Jul AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
)

SELECT f.FLAVOR
FROM FIRST_HALF f
JOIN Jul j
ON f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.TOTAL) DESC
LIMIT 3;