SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a, PATIENT p, DOCTOR d
where a.PT_NO = p.PT_NO
AND a.MDDR_ID = d.DR_ID
AND a.MCDP_CD = "CS"
AND DATE_FORMAT(a.APNT_YMD, "%Y-%m-%d") = "2022-04-13"
AND a.APNT_CNCL_YN = "N"
ORDER BY a.APNT_YMD;