SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM PATIENT p, DOCTOR d, APPOINTMENT a
WHERE p.PT_NO = a.PT_NO AND d.DR_ID = a.MDDR_ID
    AND DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
    AND a.MCDP_CD = 'CS'
    AND a.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;