WITH RECURSIVE TIME AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME
    WHERE HOUR < 23
)

SELECT t.HOUR, IFNULL(COUNT, 0) AS COUNT
FROM TIME t
LEFT OUTER JOIN (
    SELECT HOUR(a.DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS a
    GROUP BY HOUR(a.DATETIME)
) AS temp
ON t.HOUR = temp.HOUR
ORDER BY HOUR;