WITH temp AS (
    SELECT g.EMP_NO, e.EMP_NAME, AVG(SCORE) AS SCORE, e.SAL
    FROM HR_GRADE g, HR_EMPLOYEES e
    WHERE g.EMP_NO = e.EMP_NO
    GROUP BY EMP_NO
)

SELECT EMP_NO, EMP_NAME,
    CASE
        WHEN SCORE >= 96 THEN 'S'
        WHEN SCORE >= 90 THEN 'A'
        WHEN SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN SCORE >= 96 THEN SAL * 0.2
        WHEN SCORE >= 90 THEN SAL * 0.15
        WHEN SCORE >= 80 THEN SAL * 0.1
        ELSE 0
    END AS BONUS
FROM temp
ORDER BY EMP_NO;