WITH ANI AS(
    SELECT HOUR(DATETIME) AS HOUR
    FROM ANIMAL_OUTS
    WHERE DATE_FORMAT(DATETIME, '%H:%i') BETWEEN '09:00' AND '19:59'
)

SELECT HOUR, COUNT(*) AS COUNT
FROM ANI
GROUP BY HOUR
ORDER BY HOUR;