SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO i
JOIN FISH_NAME_INFO n
ON i.FISH_TYPE = n.FISH_TYPE
WHERE (i.LENGTH, i.FISH_TYPE) IN (
    SELECT MAX(LENGTH), FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY i.ID;